### ISSUE TITLE
Precompiled rootfs, tar: This does not look like a tar archive

### ISSUE THREAD

**Issue by jaromir-sukuba** [openwrt-zipit/openwrt-pxa-target#1]
Hello,
I'm trying to use ready-to-go image as per instructions on https://github.com/openwrt-zipit/openwrt-pxa-target/wiki/Installation
Unfortunately, tar issues error
```
tar: This does not look like a tar archive
tar: Skipping to next header
tar: Exiting with failure status due to previous errors
```
when trying to extract rootfs to SD card. The tar.gz2 file is 5,9MB in size. I tried to download this file more times, on different computers and different network connectivities, but the results are the same. I'm running out of ideas about what could I do differently. 

Is there a way to check for archive integrity?

**Comment by mozzwald** [comment]
You can check the sha256 sum of the files downloaded. The hashes are in the same directory at [https://mozzwald.com/zipit/openwrt/bleeding_edge/sha256sums](https://mozzwald.com/zipit/openwrt/bleeding_edge/sha256sums)

Perhaps your distros version of tar does not recognize the file is gzipped? You could first `gunzip openwrt-pxa-zipitz2-rootfs.tar.gz` then untar the file. Or, try adding the -j switch to your tar command.

**Comment by jaromir-sukuba** [comment]
Indeed, tar doesn't recognize the file to be gzipped, I'm a bit surprised by this. gunzip helped me to uncompress the archive, thanks for your prompt and helpful response.
My distribution is Linux Mint 18.1, perhaps this will serve as reference for other users running into the same problem.
